<?php

namespace ImageBundle\Repository;

use Doctrine\ORM\Query\Expr;
use Doctrine\ORM\QueryBuilder;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param int|null $bookId
     * @return QueryBuilder
     */
    public function getAvailableImagesForBookQB(?int $bookId): QueryBuilder
    {
        $qb = $this
            ->createQueryBuilder('image');

        $expr = new Expr();

        if ($bookId) {
            $expr = $expr->orX(
                $expr->isNull('image.book'),
                $expr->eq('image.book', ':bookId')
            );
            $qb = $qb->setParameter('bookId', $bookId);
        } else {
            $expr = $expr->isNull('image.book');
        }

        $qb = $qb
            ->where($expr)
            ->orderBy('image.creationDate', 'ASC');

        return $qb;
    }

}
