<?php

namespace ImageBundle\Repository;

use BookBundle\Entity\Book;
use Doctrine\ORM\QueryBuilder;
use ImageBundle\Entity\Image;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailableImagesQB(): QueryBuilder
    {
        return $this
            ->createQueryBuilder('image')
            ->where('image.book is null')
            ->orderBy('image.creationDate', 'ASC');
    }

}
