<?php

namespace ImageBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailableImagesQB(){
        return $this
            ->createQueryBuilder('image')
            ->where('image.book is null')
            ->orderBy('image.creationDate', 'ASC');
    }
}
