services:
#    google_books.example:
#        class: GoogleBooksBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  google.books.service:
    class: GoogleBooksBundle\Service\GoogleBooksService
    arguments:
      - '@service_container'
