<?php
/**
 * Created by PhpStorm.
 * User: programista
 * Date: 28.10.18
 * Time: 17:48
 */

namespace CMSBundle\Twig;


use Twig\Extension\AbstractExtension;

class BlockExtension extends AbstractExtension
{
    private $twig;

    /**
     * BlockExtension constructor.
     * @param $twig
     */
    public function __construct(\Twig_Environment $twig)
    {
        $this->twig = $twig;
    }


    public function getFunctions()
    {
        return parent::getFunctions(); // TODO: Change the autogenerated stub
    }


}