<?php

namespace BookBundle\Repository;

use BookBundle\Entity\PrintType;

/**
 * PrintTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrintTypeRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $name
     * @return PrintType
     */
    public function getPrintTypeByName($name):PrintType
    {
        $return =  $this
            ->createQueryBuilder('pt')
            ->where('pt.name = :name')
            ->setParameter('name', $name)
            ->getQuery()
            ->getSingleResult();

        return $return;
    }
}
