<?php

namespace BookBundle\Repository;

/**
 * PrintTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrintTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
