services:

    books_data_table.service:
          class: BookBundle\DataTable\BooksDataTable
          arguments: ["@doctrine.orm.entity_manager"]
          tags: [{ name: datatable, id: books }]

    books_rest_service.service:
      class: BookBundle\Service\RestService
      arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

    book.type:
      class: BookBundle\Form\BookType
      arguments: ["@doctrine.orm.entity_manager"]
      tags: [form.type]