book:
    resource: "@BookBundle/Controller/"
    type:     annotation
    prefix:   /
chat:
    resource: "@WebSocketBundle/Controller/"
    type: annotation
    prefix: /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"