#google_books:
#    resource: "@GoogleBooksBundle/Controller/"
#    type:     annotation
#    prefix:   /

#book:
#    resource: "@BookBundle/Controller/"
#    type:     annotation
#    prefix:   /

#common:
#    resource: "@CommonBundle/Controller/"
#    type:     annotation
#    prefix:   /

#operator:
#    resource: "@OperatorBundle/Controller/"
#    type:     annotation
#    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"