services:
  ws.topic.notifications:
    class: WebSocketBundle\Topic\ActiveUsersTopic
    tags:
      - { name: gos_web_socket.topic }
    arguments:
      ['@doctrine.orm.entity_manager', '@gos_web_socket.websocket.client_manipulator']
