services:
#    cms.example:
#        class: CMSBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    twig.parts:
      class: CMSBundle\Twig\BlockExtension
      tags:
        - { name: twig.extension }
      arguments:
        - '@twig'


